### ISSUE TITLE
Publish to extension marketplace

### ISSUE THREAD

**Issue by ChildishGiant** [Nyaacinth/yuescript-syntax#1]
This would make it more easily installed.

https://marketplace.visualstudio.com/VSCode

Bonus points if published to open VSX: https://open-vsx.org/

**Comment by Nyaacinth** [comment]
Since I'm not using Yuescript anymore, I would suggest you to use the official version: https://github.com/pigpigyyy/yuescript-vscode. And thanks for using this extension.
Ijo.
